var lot_lang = {
	em_s1 : '以下号码错误，已进行自动过滤',
	em_s2 : '以下号码重复，已进行自动过滤',
	bt_sel_all : "全",
	bt_sel_big : "大",
	bt_sel_small : "小",
	bt_sel_odd : "奇",
	bt_sel_even : "偶",
	bt_sel_clean : "清",
	dec_s1 : "注",
	dec_s2 : "倍",
	dec_s3 : "元",
	dec_s4 : '<span style="color:#999999">每一个号码之间请用一个 空格[ ]、逗号[,] 或者 分号[;] 隔开<span>',
	dec_s5 : "投注项详情",
	dec_s6 : "关闭",
	dec_s7 : "(当前期)",
	dec_s8 : '你确定加入 [issue] 期？',
	dec_s81 : '你确定加入？',
	dec_s9 : "投注总金额",
	dec_s10 : "同倍追号",
	dec_s11 : "翻倍追号",
	dec_s12 : "利润金额追号",
	dec_s13 : "利润率追号",
	dec_s14 : "起始倍数",
	dec_s15 : "追号期数",
	dec_s16 : "追号总金额",
	dec_s17 : "隔",
	dec_s18 : "期",
	dec_s19 : "×",
	dec_s20 : "￥",
	dec_s21 : "天",
	dec_s22 : "小时",
	dec_s23 : "分",
	dec_s24 : "删除",
	dec_s25 : "温馨提示",
	dec_s26 : '<span style="color:#999999">每注号码之间请使用逗号（，）、分号（；）或回车键隔开，每注内间隔使用空格即可。<span>',
	dec_s27 : "文件载入",
	dec_s28 : '载入文件成功',
	dec_s29 : "最低收益率",
	dec_s30 : "玩法",
	dec_s31 : "号码",
	dec_s32 : "模式",
	dec_s33 : "奖金",
	dec_s34 : "返点",
	dec_s35 : "包含",
	dec_s36 : "共计",
	dec_s37 : "返点",
	dec_s38 : "单",
	dec_s39 : "注单组合如下：",
	dec_s40 : "\u53f7\u7801\u4f4d\u7f6e:",
	dec_s41 : [ "\u4e07\u4f4d", "\u5343\u4f4d", "\u767e\u4f4d", "\u5341\u4f4d",
			"\u4e2a\u4f4d" ],
	dec_s42 : '<font color="#1456b9">任选玩法</font>',
	dec_s43 : '<font color="#1456b9">常规玩法</font>',
	dec_s44 : "点击切换",
	dec_s45 : '<span style="color:#000;margin-left:10px;"><b>\u6e29\u99a8\u63d0\u793a\uff1a</b>\u4f60\u9009\u62e9\u4e86 <b><span id="positioncount" style="color:red;">%n</span></b> \u4e2a\u4f4d\u7f6e\uff0c\u7cfb\u7edf\u81ea\u52a8\u6839\u636e\u4f4d\u7f6e\u7ec4\u5408\u6210 <b><span id="positioninfo" style="color:red;">1</span></b> \u4e2a\u65b9\u6848\u3002</span>',
	am_s3 : '已删除以下重复号码:',
	am_s4 : '没有重复号码&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
	am_s5 : '是否清空确认区中所有投注内容？',
	am_s7 : '请先添加投注内容',
	am_s8 : '请填写追号期数',
	am_s9 : '追号期数不正确，超出了最大可追号期数',
	am_s10 : '请填写倍数',
	am_s11 : '请填写相隔期数',
	am_s12 : "<strong>同倍追号</strong>:&nbsp;&nbsp;[times] 倍\n\n",
	am_s13 : "<strong>翻倍追号: </strong>\n\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;相隔 [step] 期  x [times] 倍\n\n",
	am_s14 : "确定要追号 [count] 期？",
	am_s144 : '确定要追号 [count] 期？',
	am_s15 : '当前期结束，是否要清空已投注内容?\n\n要清空已投注内容请点击"确定"，不刷新页面请点击"取消"',
	am_s16 : '获取数据失败,请刷新页面',
	am_s17 : "登陆超时，或者帐户在其他地方登陆，请重新登陆",
	am_s18 : "未到销售时间",
	am_s19 : '号码选择不完整，请重新选择',
	am_s20 : '请选择要追号的奖期',
	am_s21 : '<table><tr><td style="width:50px;"></td><td>追号奖期中,第:\n <font color="red">[errorIssue]</font> \n期倍数错误</td></tr></table>',
	am_s22 : '<div style="padding: 30px 0">正在提交数据,请稍等....</div>',
	am_s23 : '请求超时,请重试',
	am_s24 : '购买成功',
	am_s25 : '成功投注：<font color="red">[success]</font>单&nbsp;&nbsp;&nbsp;&nbsp;失败：<font color="red">[fail]</font>单',
	am_s26 : '是否需要清空所有投注项？',
	am_s27 : '数据出错',
	am_s28 : '确认区有相同的投注内容',
	am_s29 : '号码输入有误，请重新输入',
	am_s30 : '利润率错误',
	am_s31 : '多玩法不支持利润率追号，请选择单一玩法进行投注',
	am_s32 : '此玩法不支持利润率追号，请用其他追号方式',
	am_s33 : '混合圆角模式不支持利润率追号，请选择单一圆角模式',
	am_s34 : "<strong>利润率追号: </strong>\n\n&nbsp;&nbsp;&nbsp;最低利润率：[margin] ，起始倍数：[times]\n\n",
	am_s35 : '鼠标 <font class=cy>"移动"</font> 至任意行, 可查看简单信息<br/>鼠标 <font class=cy>"点击"</font> 任意行, 可查看详细信息',
	am_s99 : '<table style="width:auto;"><tr><td>[msg]</td></tr></table>',
	am_s100 : '',
	test : ""
};